/**
 * AI对抗协议 - 类型定义
 * AI Adversarial Protocol - Type Definitions
 */

// ========== Provider配置 ==========
export interface ProviderConfig {
  type: 'native' | 'custom';  // native=官方API, custom=第三方中转
  apiKey: string;
  baseUrl?: string;  // custom模式下使用
  model?: string;  // 可选模型覆盖
}

// ========== 应用设置 ==========
export interface AppSettings {
  claude: ProviderConfig;
  openai: ProviderConfig;
  sessionBudget?: number;  // 会话预算限制（美元）
}

// ========== 消息和挑战 ==========
export interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  isClaude?: boolean;  // true=Claude, false=OpenAI/Codex, 用户消息无此字段
  timestamp: number;
  // Phase 2 - Feature 1: 串行互相引用
  roundType?: RoundType;
  referencesTo?: string[];  // 引用的消息ID列表
  isResponseTo?: string;    // 如果是串行回应，指向对方的消息ID
  // Phase 2 - Feature 3: 思维过程可视化
  thinkingBlocks?: ThinkingBlock[];  // 思维过程
}

// 轮次类型
export type RoundType = 'parallel' | 'serial-a-first' | 'serial-b-first';

export interface Challenge {
  id: string;
  messageIndex: number;  // 挑战第几条消息
  reason: string;  // 为什么挑刺（用户手动填写）
  timestamp: number;
  // Phase 2 扩展字段
  targetMessageId?: string;     // 被挑刺的消息ID
  challengerAi?: 'claude' | 'openai' | 'user';  // 挑战者
  challengeType?: 'factual-error' | 'logical-flaw' | 'omission' | 'unclear' | 'other';  // 挑战类型
  severity?: 'low' | 'medium' | 'high';  // 严重性
  targetSegment?: string;        // 被挑刺的具体文本片段
  isAutoGenerated?: boolean;     // 是否是自动挑刺
  status?: 'pending' | 'accepted' | 'rejected' | 'debated';  // 挑战状态
}

// ========== 对话状态 ==========
export interface DebateState {
  messages: Message[];
  challenges: Challenge[];
  isStreaming: boolean;
  tokenCount: {
    claude: number;
    openai: number;
  };
  // Phase 2 - Feature 1: 串行互相引用
  currentRound?: number;
  roundType?: RoundType;
  firstResponder?: 'claude' | 'openai';  // 串行模式下先响应的AI
}

// 串行引用配置
export interface SerialReferenceConfig {
  enabled: boolean;
  mode: 'always-serial' | 'hybrid' | 'manual-toggle';
  firstResponder: 'auto' | 'claude' | 'openai';  // auto = 轮流
}

// ========== 思维过程可视化 (Phase 2 - Feature 3) ==========

export interface ThinkingBlock {
  id: string;
  messageId: string;           // 关联的消息ID
  content: string;             // 思维内容
  order: number;               // 顺序（如果有多个thinking块）
  timestamp: number;
  source: 'explicit-tag' | 'extended-thinking' | 'o1-reasoning';
}

export interface ThinkingVisualizationConfig {
  enabled: boolean;
  displayMode: 'inline' | 'sidebar' | 'modal';
  collapseByDefault: boolean;
  highlightKeyInsights: boolean;    // 高亮关键洞察
}

// ========== 自动挑刺 (Phase 2 - Feature 2) ==========

export interface AutoChallengeConfig {
  enabled: boolean;
  threshold: number;             // 置信度阈值 (0-1)
  maxChallengesPerRound: number; // 每轮最多挑刺次数
  allowSelfChallenge: boolean;   // 是否允许AI自我挑刺
}

export interface AutoChallengeRequest {
  messageA: Message;  // Claude的输出
  messageB: Message;  // OpenAI的输出
  config: AutoChallengeConfig;
}

export interface AutoChallengeResponse {
  challenges: Challenge[];
  summary: {
    total: number;
    byType: Record<string, number>;
    bySeverity: Record<string, number>;
  };
}

// ========== API请求/响应 ==========
export interface ChatRequest {
  question: string;
  debateState: DebateState;
  provider?: ProviderConfig;  // 可选，用于覆盖.env配置
  // Phase 2 - Feature 1: 串行互相引用
  opponentMessage?: Message;  // 对方当前轮次的输出（如果是串行模式）
  serialConfig?: SerialReferenceConfig;  // 串行配置
}

export interface ChatStreamChunk {
  id: string;
  content: string;
  isClaude: boolean;
  done: boolean;
  timestamp: number;
}

// ========== 审计质量评分 (Phase 2 - Feature 5) ==========

export interface AuditMetrics {
  aiId: string;              // 'claude' | 'openai' | ...
  totalMessages: number;     // 总输出数
  totalChallenges: number;   // 被挑刺总数
  challengesByType: {
    factualError: number;
    logicalFlaw: number;
    omission: number;
    unclear: number;
    other: number;
  };
  challengesBySeverity: {
    high: number;
    medium: number;
    low: number;
  };
  acceptedChallenges: number;  // 被接受的挑刺数
  rejectedChallenges: number;  // 被拒绝的挑刺数
  reliabilityScore: number;    // 0-100
  lastUpdated: number;
}

export interface AuditHistoryEntry {
  timestamp: number;
  aiId: string;
  challengeId: string;
  action: 'challenged' | 'accepted' | 'rejected';
  scoreChange: number;  // 评分变化
}

export interface AuditState {
  metrics: Record<string, AuditMetrics>;  // aiId -> metrics
  history: AuditHistoryEntry[];
}

// ========== 多AI投票 (Phase 2 - Feature 4) ==========

// 支持的AI provider类型
export type AIProvider = 'claude' | 'openai' | 'gemini' | 'local';

// AI provider配置
export interface AIProviderConfig {
  id: AIProvider;
  name: string;              // 显示名称
  enabled: boolean;          // 是否启用
  type: 'anthropic' | 'openai' | 'google' | 'ollama';  // API类型
  apiKey?: string;
  baseUrl?: string;
  model?: string;
  // 权重配置（用于投票）
  weight?: number;           // 投票权重 (0-1, 默认1.0)
  specialty?: string[];      // 专长领域（可选，用于加权投票）
}

// 投票配置
export interface VotingConfig {
  enabled: boolean;
  mode: 'majority' | 'weighted' | 'consensus' | 'unanimous';  // 投票模式
  threshold: number;         // 共识阈值 (0-1, 多数: 0.5, 一致: 1.0)
  tiebreaker: 'first' | 'random' | 'abstain';  // 平局处理
  allowSelfVote: boolean;   // 是否允许AI给自己投票
}

// 投票主题
export interface VoteTopic {
  id: string;
  type: 'best-answer' | 'fact-check' | 'challenge-validation' | 'consensus';
  description: string;
  options: string[];         // 选项（消息ID或陈述）
  createdAt: number;
}

// 单个投票
export interface Vote {
  id: string;
  topicId: string;
  voterId: AIProvider;       // 投票者
  choice: string;            // 选择的选项
  confidence?: number;       // 置信度 (0-1)
  reasoning?: string;        // 投票理由
  timestamp: number;
}

// 投票结果
export interface VotingResult {
  topicId: string;
  votes: Vote[];
  totals: Record<string, number>;  // 每个选项的得票数
  winner?: string;           // 获胜选项
  consensusLevel: number;    // 共识程度 (0-1)
  isTie: boolean;
  isUnanimous: boolean;
  requiresReview: boolean;   // 是否需要人工审查
}

// 投票请求
export interface VotingRequest {
  messages: Message[];       // 候选答案（通常是多个AI的输出）
  topic: VoteTopic;
  providers: AIProvider[];   // 参与投票的AI列表
  config: VotingConfig;
  context?: string;          // 额外上下文（如原始问题）
}

// 投票响应
export interface VotingResponse {
  result: VotingResult;
  votes: Vote[];
  summary: {
    totalVotes: number;
    participatedProviders: AIProvider[];
    consensusReached: boolean;
    timeElapsed: number;
  };
}
