/**
 * 自动挑刺解析器
 * Auto-Challenge Parser
 */

import { Challenge } from '@/lib/types';

export interface ParsedChallenge {
  type: 'factual-error' | 'logical-flaw' | 'omission' | 'unclear' | 'other';
  severity: 'low' | 'medium' | 'high';
  targetSegment: string;
  reason: string;
  confidence: number;
}

// 有效的类型枚举
const VALID_CHALLENGE_TYPES = ['factual-error', 'logical-flaw', 'omission', 'unclear', 'other'] as const;
const VALID_SEVERITY_LEVELS = ['low', 'medium', 'high'] as const;

/**
 * 解析AI返回的挑刺JSON
 */
export function parseChallengeResponse(
  response: string,
  challengerAi: 'claude' | 'openai',
  targetMessageId: string
): { challenges: Challenge[]; error?: string } {
  try {
    // 尝试提取JSON（可能包含在markdown代码块中）
    let jsonStr = response.trim();

    // 移除markdown代码块标记
    jsonStr = jsonStr.replace(/```json\n?/g, '').replace(/```\n?/g, '');

    // 提取JSON部分（如果有额外文本）
    const jsonMatch = jsonStr.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      jsonStr = jsonMatch[0];
    }

    const parsed = JSON.parse(jsonStr);

    if (!parsed.challenges || !Array.isArray(parsed.challenges)) {
      return {
        challenges: [],
        error: 'Invalid response format: missing challenges array',
      };
    }

    // 转换为Challenge对象，同时验证枚举值
    const challenges: Challenge[] = parsed.challenges
      .filter((c: any) => {
        // 验证type是否有效
        if (c.type && !VALID_CHALLENGE_TYPES.includes(c.type)) {
          console.warn(`Invalid challenge type: ${c.type}, skipping`);
          return false;
        }
        // 验证severity是否有效
        if (c.severity && !VALID_SEVERITY_LEVELS.includes(c.severity)) {
          console.warn(`Invalid severity: ${c.severity}, skipping`);
          return false;
        }
        return true;
      })
      .map((c: any, index: number) => ({
        id: `auto-challenge-${Date.now()}-${index}`,
        messageIndex: 0, // 稍后填充
        reason: c.reason,
        timestamp: Date.now(),
        targetMessageId,
        challengerAi,
        challengeType: c.type,
        severity: c.severity,
        targetSegment: c.targetSegment,
        isAutoGenerated: true,
        status: 'pending' as const,
      }))
      .filter((c: ParsedChallenge) => c.confidence >= 0.7); // 置信度过滤

    return { challenges };
  } catch (error) {
    return {
      challenges: [],
      error: `JSON parse error: ${error instanceof Error ? error.message : 'Unknown error'}`,
    };
  }
}

/**
 * 去重相似的挑刺
 */
export function deduplicateChallenges(challenges: Challenge[]): Challenge[] {
  const seen = new Set<string>();
  return challenges.filter((c) => {
    const key = `${c.targetMessageId}-${c.targetSegment}-${c.challengeType}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

/**
 * 限制挑刺数量
 */
export function limitChallenges(
  challenges: Challenge[],
  maxChallenges: number
): Challenge[] {
  return challenges.slice(0, maxChallenges);
}

/**
 * 按置信度和严重性排序
 */
export function sortChallenges(challenges: Challenge[]): Challenge[] {
  return [...challenges].sort((a, b) => {
    // 先按严重性排序
    const severityOrder = { high: 3, medium: 2, low: 1 };
    const severityDiff = (severityOrder[b.severity || 'low'] || 0) - (severityOrder[a.severity || 'low'] || 0);

    if (severityDiff !== 0) return severityDiff;

    // 严重性相同时按置信度排序
    // 这里我们没有confidence字段在Challenge中，所以保持原顺序
    return 0;
  });
}

/**
 * 验证挑刺内容
 */
export function validateChallenge(challenge: Challenge): boolean {
  // 检查必需字段
  if (!challenge.reason || challenge.reason.trim().length === 0) {
    return false;
  }

  if (!challenge.challengeType) {
    return false;
  }

  if (!challenge.severity) {
    return false;
  }

  // 检查targetSegment长度
  if (challenge.targetSegment && challenge.targetSegment.length > 200) {
    return false;
  }

  // 检查reason长度
  if (challenge.reason.length > 500) {
    return false;
  }

  return true;
}

/**
 * 过滤无效挑刺
 */
export function filterValidChallenges(challenges: Challenge[]): Challenge[] {
  return challenges.filter(validateChallenge);
}

/**
 * 计算挑刺统计
 */
export function calculateChallengeSummary(challenges: Challenge[]) {
  const summary = {
    total: challenges.length,
    byType: {} as Record<string, number>,
    bySeverity: {} as Record<string, number>,
  };

  challenges.forEach((c) => {
    // 按类型统计
    if (c.challengeType) {
      summary.byType[c.challengeType] = (summary.byType[c.challengeType] || 0) + 1;
    }

    // 按严重性统计
    if (c.severity) {
      summary.bySeverity[c.severity] = (summary.bySeverity[c.severity] || 0) + 1;
    }
  });

  return summary;
}
