import { describe, it, expect, vi } from 'vitest';
import { fireEvent, render, screen } from '@testing-library/react';
import AutoChallengePanel from './AutoChallengePanel';

describe('AutoChallengePanel', () => {
  const challenges = [
    {
      id: 'challenge-1',
      messageIndex: 0,
      reason: 'Missing detail',
      timestamp: Date.now(),
      challengerAi: 'claude' as const,
      challengeType: 'omission' as const,
      severity: 'medium' as const,
      targetSegment: 'Some target text',
      isAutoGenerated: true,
      status: 'pending' as const,
    },
  ];

  it('calls accept action handler', () => {
    const onChallengeAction = vi.fn();
    render(<AutoChallengePanel challenges={challenges} onChallengeAction={onChallengeAction} />);

    fireEvent.click(screen.getByText('✅ 接受'));
    expect(onChallengeAction).toHaveBeenCalledWith('challenge-1', 'accept');
  });

  it('calls reject action handler', () => {
    const onChallengeAction = vi.fn();
    render(<AutoChallengePanel challenges={challenges} onChallengeAction={onChallengeAction} />);

    fireEvent.click(screen.getByText('❌ 忽略'));
    expect(onChallengeAction).toHaveBeenCalledWith('challenge-1', 'reject');
  });

  it('calls debate action handler', () => {
    const onChallengeAction = vi.fn();
    render(<AutoChallengePanel challenges={challenges} onChallengeAction={onChallengeAction} />);

    fireEvent.click(screen.getByText('🔄 展开辩论'));
    expect(onChallengeAction).toHaveBeenCalledWith('challenge-1', 'debate');
  });
});
