/**
 * 自动挑刺面板
 * Auto-Challenge Panel
 *
 * 显示AI自动生成的挑刺
 */

'use client';

import { useState } from 'react';
import { Challenge } from '@/lib/types';

interface AutoChallengePanelProps {
  challenges: Challenge[];
  onChallengeAction: (challengeId: string, action: 'accept' | 'reject' | 'debate') => void;
}

export default function AutoChallengePanel({
  challenges,
  onChallengeAction,
}: AutoChallengePanelProps) {
  const [expandedChallenge, setExpandedChallenge] = useState<string | null>(null);

  if (challenges.length === 0) {
    return null;
  }

  const getSeverityColor = (severity?: string) => {
    switch (severity) {
      case 'high':
        return 'border-red-500 bg-red-50';
      case 'medium':
        return 'border-yellow-500 bg-yellow-50';
      case 'low':
        return 'border-blue-500 bg-blue-50';
      default:
        return 'border-gray-500 bg-gray-50';
    }
  };

  const getSeverityLabel = (severity?: string) => {
    switch (severity) {
      case 'high':
        return '高严重性';
      case 'medium':
        return '中等';
      case 'low':
        return '低';
      default:
        return '未知';
    }
  };

  const getTypeLabel = (type?: string) => {
    if (type === 'factual-error') return '事实错误';
    if (type === 'logical-flaw') return '逻辑漏洞';
    if (type === 'omission') return '重要遗漏';
    if (type === 'unclear') return '表述不清';
    return '其他';
  };

  const getTypeEmoji = (type?: string) => {
    if (type === 'factual-error') return '❌';
    if (type === 'logical-flaw') return '🔀';
    if (type === 'omission') return '⚠️';
    if (type === 'unclear') return '❓';
    return '📝';
  };

  const getChallengerLabel = (ai?: string) => {
    if (ai === 'claude') return 'Claude';
    if (ai === 'openai') return 'OpenAI';
    return 'AI';
  };

  return (
    <div className="bg-white rounded-lg shadow-md p-4 mb-6">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-lg font-semibold flex items-center gap-2">
          🤖 自动挑刺
          <span className="text-sm font-normal text-gray-500">({challenges.length} 条)</span>
        </h3>
      </div>

      <div className="space-y-3">
        {challenges.map((challenge) => (
          <div
            key={challenge.id}
            className={`border-l-4 ${getSeverityColor(challenge.severity)} p-3 rounded-r`}
          >
            {/* 头部 */}
            <div className="flex items-start justify-between mb-2">
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-lg">
                    {getTypeEmoji(challenge.challengeType)}
                  </span>
                  <span className="font-medium text-gray-800">
                    {getChallengerLabel(challenge.challengerAi)}挑战了
                    {challenge.challengerAi === 'claude' ? 'OpenAI' : 'Claude'}
                  </span>
                  <span className={`px-2 py-0.5 rounded text-xs font-medium ${
                    challenge.severity === 'high' ? 'bg-red-100 text-red-700' :
                    challenge.severity === 'medium' ? 'bg-yellow-100 text-yellow-700' :
                    'bg-blue-100 text-blue-700'
                  }`}>
                    {getSeverityLabel(challenge.severity)}
                  </span>
                </div>
                <div className="text-sm text-gray-600">
                  类型: {getTypeLabel(challenge.challengeType)}
                </div>
              </div>
              <button
                onClick={() => setExpandedChallenge(
                  expandedChallenge === challenge.id ? null : challenge.id
                )}
                className="text-gray-400 hover:text-gray-600"
              >
                {expandedChallenge === challenge.id ? '▼' : '▶'}
              </button>
            </div>

            {/* 目标片段 */}
            {challenge.targetSegment && (
              <div className="mb-2 p-2 bg-white rounded border border-gray-200">
                <div className="text-xs text-gray-500 mb-1">目标片段:</div>
                <div className="text-sm italic text-gray-700">
                  "{challenge.targetSegment}"
                </div>
              </div>
            )}

            {/* 原因 */}
            <div className="mb-3 text-sm text-gray-700">
              <div className="font-medium mb-1">原因:</div>
              <div>{challenge.reason}</div>
            </div>

            {/* 展开的详细信息 */}
            {expandedChallenge === challenge.id && (
              <div className="mb-3 p-3 bg-gray-50 rounded text-xs text-gray-600 space-y-1">
                <div>挑刺ID: {challenge.id}</div>
                <div>时间戳: {new Date(challenge.timestamp).toLocaleString()}</div>
                {challenge.isAutoGenerated && (
                  <div>✨ 自动生成</div>
                )}
              </div>
            )}

            {/* 操作按钮 */}
            <div className="flex gap-2">
              <button
                onClick={() => onChallengeAction(challenge.id, 'accept')}
                className="flex-1 px-3 py-1.5 bg-green-500 hover:bg-green-600 text-white rounded text-sm font-medium"
              >
                ✅ 接受
              </button>
              <button
                onClick={() => onChallengeAction(challenge.id, 'reject')}
                className="flex-1 px-3 py-1.5 bg-gray-500 hover:bg-gray-600 text-white rounded text-sm font-medium"
              >
                ❌ 忽略
              </button>
              <button
                onClick={() => onChallengeAction(challenge.id, 'debate')}
                className="flex-1 px-3 py-1.5 bg-blue-500 hover:bg-blue-600 text-white rounded text-sm font-medium"
              >
                🔄 展开辩论
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* 提示信息 */}
      <div className="mt-4 p-3 bg-blue-50 rounded text-sm text-blue-700">
        <p>💡 <strong>提示:</strong></p>
        <ul className="list-disc list-inside mt-1 space-y-1">
          <li>接受挑刺后，将记录到审计评分中</li>
          <li>忽略挑刺将不会影响评分</li>
          <li>展开辩论可以让两个AI就此问题继续讨论</li>
        </ul>
      </div>
    </div>
  );
}
